global using Carter;
global using MediatR;
global using Mapster;
global using Marten;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using BuildingBlocks.Behaviors;
global using BuildingBlocks.Exceptions.Handler; 
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;